#!/usr/bin/env bash

# Optional companion to AeroSpace. Install with:
#   brew tap FelixKratz/formulae
#   brew install borders

options=(
  style=round
  width=6.0
  hidpi=on
  active_color=0xc0e2e2e3
  inactive_color=0xc02c2e34
  background_color=0x302c2e34
)

borders "${options[@]}"
