[providers.bitwarden]
type = "bitwarden"

[providers.age]
type = "age"
recipients = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOBc1KWo4iBvD7dDrDGSfs6Y8JDfJjiy0Urh6xp+bg80 aagaardbs@gmail.com",
]

[secrets]
