onboarding = false

[terminal]
shell_mode = "auto"
new_cwd = "follow"

[keys]
prefix = "ctrl+space"
toggle_sidebar = "ctrl+b"
detach = "ctrl+q"
reload_config = "ctrl+e"
remote_image_paste = "ctrl+v"

focus_pane_left = "ctrl+left"
focus_pane_down = "ctrl+down"
focus_pane_up = "ctrl+up"
focus_pane_right = "ctrl+right"

split_vertical = "ctrl+d"
split_horizontal = "ctrl+c"
close_pane = "ctrl+x"
resize_mode = "ctrl+r"

new_tab = "ctrl+t"
previous_tab = "ctrl+comma"
next_tab = "ctrl+period"
close_tab = "ctrl+w"

last_pane = "prefix+tab"

[ui]
prompt_new_tab_name = false
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"
delay_seconds = 1

[ui.toast.clipboard]
enabled = true
position = "bottom-center"

[ui.sound]
enabled = true

[remote]
manage_ssh_config = true

[advanced]
scrollback_limit_bytes = 10000000

[session]
resume_agents_on_restore = true

[experimental]
switch_ascii_input_source_in_prefix = true
